#include "keccak/config.h"
#include "keccak/keccak/keccak-1600.h"
#include "keccak/keccak/keccakp-1600.h"

#include <stdint.h>

static KINLINE int _keccakp(register uint64_t* const restrict state,
                            register const uint8_t rounds) {
  if ((rounds > 24) || (rounds & 1)) {
    return -1;
  }

  register uint64_t Aba, Abe, Abi, Abo, Abu;
  register uint64_t Aga, Age, Agi, Ago, Agu;
  register uint64_t Aka, Ake, Aki, Ako, Aku;
  register uint64_t Ama, Ame, Ami, Amo, Amu;
  register uint64_t Asa, Ase, Asi, Aso, Asu;
  register uint64_t Bba, Bbe, Bbi, Bbo, Bbu;
  register uint64_t Bga, Bge, Bgi, Bgo, Bgu;
  register uint64_t Bka, Bke, Bki, Bko, Bku;
  register uint64_t Bma, Bme, Bmi, Bmo, Bmu;
  register uint64_t Bsa, Bse, Bsi, Bso, Bsu;
  register uint64_t Ca, Ce, Ci, Co, Cu;
  register uint64_t Da, De, Di, Do, Du;
  register uint64_t Eba, Ebe, Ebi, Ebo, Ebu;
  register uint64_t Ega, Ege, Egi, Ego, Egu;
  register uint64_t Eka, Eke, Eki, Eko, Eku;
  register uint64_t Ema, Eme, Emi, Emo, Emu;
  register uint64_t Esa, Ese, Esi, Eso, Esu;

  register uint8_t i;

  Aba = state[0];
  Abe = state[1];
  Abi = state[2];
  Abo = state[3];
  Abu = state[4];
  Aga = state[5];
  Age = state[6];
  Agi = state[7];
  Ago = state[8];
  Agu = state[9];
  Aka = state[10];
  Ake = state[11];
  Aki = state[12];
  Ako = state[13];
  Aku = state[14];
  Ama = state[15];
  Ame = state[16];
  Ami = state[17];
  Amo = state[18];
  Amu = state[19];
  Asa = state[20];
  Ase = state[21];
  Asi = state[22];
  Aso = state[23];
  Asu = state[24];

  Ca = Aba ^ Aga ^ Aka ^ Ama ^ Asa;
  Ce = Abe ^ Age ^ Ake ^ Ame ^ Ase;
  Ci = Abi ^ Agi ^ Aki ^ Ami ^ Asi;
  Co = Abo ^ Ago ^ Ako ^ Amo ^ Aso;
  Cu = Abu ^ Agu ^ Aku ^ Amu ^ Asu;
  for (i = (24 - rounds); i < rounds; i += 2) {
    Da = Cu ^ ((((uint64_t)Ce) << 1) ^ (((uint64_t)Ce) >> (64 - 1)));
    De = Ca ^ ((((uint64_t)Ci) << 1) ^ (((uint64_t)Ci) >> (64 - 1)));
    Di = Ce ^ ((((uint64_t)Co) << 1) ^ (((uint64_t)Co) >> (64 - 1)));
    Do = Ci ^ ((((uint64_t)Cu) << 1) ^ (((uint64_t)Cu) >> (64 - 1)));
    Du = Co ^ ((((uint64_t)Ca) << 1) ^ (((uint64_t)Ca) >> (64 - 1)));
    Aba ^= Da;
    Bba = Aba;
    Age ^= De;
    Bbe = ((((uint64_t)Age) << 44) ^ (((uint64_t)Age) >> (64 - 44)));
    Aki ^= Di;
    Bbi = ((((uint64_t)Aki) << 43) ^ (((uint64_t)Aki) >> (64 - 43)));
    Amo ^= Do;
    Bbo = ((((uint64_t)Amo) << 21) ^ (((uint64_t)Amo) >> (64 - 21)));
    Asu ^= Du;
    Bbu = ((((uint64_t)Asu) << 14) ^ (((uint64_t)Asu) >> (64 - 14)));
    Eba = Bba ^ ((~Bbe) & Bbi);
    Eba ^= round_constants[i];
    Ca = Eba;
    Ebe = Bbe ^ ((~Bbi) & Bbo);
    Ce = Ebe;
    Ebi = Bbi ^ ((~Bbo) & Bbu);
    Ci = Ebi;
    Ebo = Bbo ^ ((~Bbu) & Bba);
    Co = Ebo;
    Ebu = Bbu ^ ((~Bba) & Bbe);
    Cu = Ebu;
    Abo ^= Do;
    Bga = ((((uint64_t)Abo) << 28) ^ (((uint64_t)Abo) >> (64 - 28)));
    Agu ^= Du;
    Bge = ((((uint64_t)Agu) << 20) ^ (((uint64_t)Agu) >> (64 - 20)));
    Aka ^= Da;
    Bgi = ((((uint64_t)Aka) << 3) ^ (((uint64_t)Aka) >> (64 - 3)));
    Ame ^= De;
    Bgo = ((((uint64_t)Ame) << 45) ^ (((uint64_t)Ame) >> (64 - 45)));
    Asi ^= Di;
    Bgu = ((((uint64_t)Asi) << 61) ^ (((uint64_t)Asi) >> (64 - 61)));
    Ega = Bga ^ ((~Bge) & Bgi);
    Ca ^= Ega;
    Ege = Bge ^ ((~Bgi) & Bgo);
    Ce ^= Ege;
    Egi = Bgi ^ ((~Bgo) & Bgu);
    Ci ^= Egi;
    Ego = Bgo ^ ((~Bgu) & Bga);
    Co ^= Ego;
    Egu = Bgu ^ ((~Bga) & Bge);
    Cu ^= Egu;
    Abe ^= De;
    Bka = ((((uint64_t)Abe) << 1) ^ (((uint64_t)Abe) >> (64 - 1)));
    Agi ^= Di;
    Bke = ((((uint64_t)Agi) << 6) ^ (((uint64_t)Agi) >> (64 - 6)));
    Ako ^= Do;
    Bki = ((((uint64_t)Ako) << 25) ^ (((uint64_t)Ako) >> (64 - 25)));
    Amu ^= Du;
    Bko = ((((uint64_t)Amu) << 8) ^ (((uint64_t)Amu) >> (64 - 8)));
    Asa ^= Da;
    Bku = ((((uint64_t)Asa) << 18) ^ (((uint64_t)Asa) >> (64 - 18)));
    Eka = Bka ^ ((~Bke) & Bki);
    Ca ^= Eka;
    Eke = Bke ^ ((~Bki) & Bko);
    Ce ^= Eke;
    Eki = Bki ^ ((~Bko) & Bku);
    Ci ^= Eki;
    Eko = Bko ^ ((~Bku) & Bka);
    Co ^= Eko;
    Eku = Bku ^ ((~Bka) & Bke);
    Cu ^= Eku;
    Abu ^= Du;
    Bma = ((((uint64_t)Abu) << 27) ^ (((uint64_t)Abu) >> (64 - 27)));
    Aga ^= Da;
    Bme = ((((uint64_t)Aga) << 36) ^ (((uint64_t)Aga) >> (64 - 36)));
    Ake ^= De;
    Bmi = ((((uint64_t)Ake) << 10) ^ (((uint64_t)Ake) >> (64 - 10)));
    Ami ^= Di;
    Bmo = ((((uint64_t)Ami) << 15) ^ (((uint64_t)Ami) >> (64 - 15)));
    Aso ^= Do;
    Bmu = ((((uint64_t)Aso) << 56) ^ (((uint64_t)Aso) >> (64 - 56)));
    Ema = Bma ^ ((~Bme) & Bmi);
    Ca ^= Ema;
    Eme = Bme ^ ((~Bmi) & Bmo);
    Ce ^= Eme;
    Emi = Bmi ^ ((~Bmo) & Bmu);
    Ci ^= Emi;
    Emo = Bmo ^ ((~Bmu) & Bma);
    Co ^= Emo;
    Emu = Bmu ^ ((~Bma) & Bme);
    Cu ^= Emu;
    Abi ^= Di;
    Bsa = ((((uint64_t)Abi) << 62) ^ (((uint64_t)Abi) >> (64 - 62)));
    Ago ^= Do;
    Bse = ((((uint64_t)Ago) << 55) ^ (((uint64_t)Ago) >> (64 - 55)));
    Aku ^= Du;
    Bsi = ((((uint64_t)Aku) << 39) ^ (((uint64_t)Aku) >> (64 - 39)));
    Ama ^= Da;
    Bso = ((((uint64_t)Ama) << 41) ^ (((uint64_t)Ama) >> (64 - 41)));
    Ase ^= De;
    Bsu = ((((uint64_t)Ase) << 2) ^ (((uint64_t)Ase) >> (64 - 2)));
    Esa = Bsa ^ ((~Bse) & Bsi);
    Ca ^= Esa;
    Ese = Bse ^ ((~Bsi) & Bso);
    Ce ^= Ese;
    Esi = Bsi ^ ((~Bso) & Bsu);
    Ci ^= Esi;
    Eso = Bso ^ ((~Bsu) & Bsa);
    Co ^= Eso;
    Esu = Bsu ^ ((~Bsa) & Bse);
    Cu ^= Esu;
    Da = Cu ^ ((((uint64_t)Ce) << 1) ^ (((uint64_t)Ce) >> (64 - 1)));
    De = Ca ^ ((((uint64_t)Ci) << 1) ^ (((uint64_t)Ci) >> (64 - 1)));
    Di = Ce ^ ((((uint64_t)Co) << 1) ^ (((uint64_t)Co) >> (64 - 1)));
    Do = Ci ^ ((((uint64_t)Cu) << 1) ^ (((uint64_t)Cu) >> (64 - 1)));
    Du = Co ^ ((((uint64_t)Ca) << 1) ^ (((uint64_t)Ca) >> (64 - 1)));
    Eba ^= Da;
    Bba = Eba;
    Ege ^= De;
    Bbe = ((((uint64_t)Ege) << 44) ^ (((uint64_t)Ege) >> (64 - 44)));
    Eki ^= Di;
    Bbi = ((((uint64_t)Eki) << 43) ^ (((uint64_t)Eki) >> (64 - 43)));
    Emo ^= Do;
    Bbo = ((((uint64_t)Emo) << 21) ^ (((uint64_t)Emo) >> (64 - 21)));
    Esu ^= Du;
    Bbu = ((((uint64_t)Esu) << 14) ^ (((uint64_t)Esu) >> (64 - 14)));
    Aba = Bba ^ ((~Bbe) & Bbi);
    Aba ^= round_constants[i + 1];
    Ca = Aba;
    Abe = Bbe ^ ((~Bbi) & Bbo);
    Ce = Abe;
    Abi = Bbi ^ ((~Bbo) & Bbu);
    Ci = Abi;
    Abo = Bbo ^ ((~Bbu) & Bba);
    Co = Abo;
    Abu = Bbu ^ ((~Bba) & Bbe);
    Cu = Abu;
    Ebo ^= Do;
    Bga = ((((uint64_t)Ebo) << 28) ^ (((uint64_t)Ebo) >> (64 - 28)));
    Egu ^= Du;
    Bge = ((((uint64_t)Egu) << 20) ^ (((uint64_t)Egu) >> (64 - 20)));
    Eka ^= Da;
    Bgi = ((((uint64_t)Eka) << 3) ^ (((uint64_t)Eka) >> (64 - 3)));
    Eme ^= De;
    Bgo = ((((uint64_t)Eme) << 45) ^ (((uint64_t)Eme) >> (64 - 45)));
    Esi ^= Di;
    Bgu = ((((uint64_t)Esi) << 61) ^ (((uint64_t)Esi) >> (64 - 61)));
    Aga = Bga ^ ((~Bge) & Bgi);
    Ca ^= Aga;
    Age = Bge ^ ((~Bgi) & Bgo);
    Ce ^= Age;
    Agi = Bgi ^ ((~Bgo) & Bgu);
    Ci ^= Agi;
    Ago = Bgo ^ ((~Bgu) & Bga);
    Co ^= Ago;
    Agu = Bgu ^ ((~Bga) & Bge);
    Cu ^= Agu;
    Ebe ^= De;
    Bka = ((((uint64_t)Ebe) << 1) ^ (((uint64_t)Ebe) >> (64 - 1)));
    Egi ^= Di;
    Bke = ((((uint64_t)Egi) << 6) ^ (((uint64_t)Egi) >> (64 - 6)));
    Eko ^= Do;
    Bki = ((((uint64_t)Eko) << 25) ^ (((uint64_t)Eko) >> (64 - 25)));
    Emu ^= Du;
    Bko = ((((uint64_t)Emu) << 8) ^ (((uint64_t)Emu) >> (64 - 8)));
    Esa ^= Da;
    Bku = ((((uint64_t)Esa) << 18) ^ (((uint64_t)Esa) >> (64 - 18)));
    Aka = Bka ^ ((~Bke) & Bki);
    Ca ^= Aka;
    Ake = Bke ^ ((~Bki) & Bko);
    Ce ^= Ake;
    Aki = Bki ^ ((~Bko) & Bku);
    Ci ^= Aki;
    Ako = Bko ^ ((~Bku) & Bka);
    Co ^= Ako;
    Aku = Bku ^ ((~Bka) & Bke);
    Cu ^= Aku;
    Ebu ^= Du;
    Bma = ((((uint64_t)Ebu) << 27) ^ (((uint64_t)Ebu) >> (64 - 27)));
    Ega ^= Da;
    Bme = ((((uint64_t)Ega) << 36) ^ (((uint64_t)Ega) >> (64 - 36)));
    Eke ^= De;
    Bmi = ((((uint64_t)Eke) << 10) ^ (((uint64_t)Eke) >> (64 - 10)));
    Emi ^= Di;
    Bmo = ((((uint64_t)Emi) << 15) ^ (((uint64_t)Emi) >> (64 - 15)));
    Eso ^= Do;
    Bmu = ((((uint64_t)Eso) << 56) ^ (((uint64_t)Eso) >> (64 - 56)));
    Ama = Bma ^ ((~Bme) & Bmi);
    Ca ^= Ama;
    Ame = Bme ^ ((~Bmi) & Bmo);
    Ce ^= Ame;
    Ami = Bmi ^ ((~Bmo) & Bmu);
    Ci ^= Ami;
    Amo = Bmo ^ ((~Bmu) & Bma);
    Co ^= Amo;
    Amu = Bmu ^ ((~Bma) & Bme);
    Cu ^= Amu;
    Ebi ^= Di;
    Bsa = ((((uint64_t)Ebi) << 62) ^ (((uint64_t)Ebi) >> (64 - 62)));
    Ego ^= Do;
    Bse = ((((uint64_t)Ego) << 55) ^ (((uint64_t)Ego) >> (64 - 55)));
    Eku ^= Du;
    Bsi = ((((uint64_t)Eku) << 39) ^ (((uint64_t)Eku) >> (64 - 39)));
    Ema ^= Da;
    Bso = ((((uint64_t)Ema) << 41) ^ (((uint64_t)Ema) >> (64 - 41)));
    Ese ^= De;
    Bsu = ((((uint64_t)Ese) << 2) ^ (((uint64_t)Ese) >> (64 - 2)));
    Asa = Bsa ^ ((~Bse) & Bsi);
    Ca ^= Asa;
    Ase = Bse ^ ((~Bsi) & Bso);
    Ce ^= Ase;
    Asi = Bsi ^ ((~Bso) & Bsu);
    Ci ^= Asi;
    Aso = Bso ^ ((~Bsu) & Bsa);
    Co ^= Aso;
    Asu = Bsu ^ ((~Bsa) & Bse);
    Cu ^= Asu;
  }

  state[0] = Aba;
  state[1] = Abe;
  state[2] = Abi;
  state[3] = Abo;
  state[4] = Abu;
  state[5] = Aga;
  state[6] = Age;
  state[7] = Agi;
  state[8] = Ago;
  state[9] = Agu;
  state[10] = Aka;
  state[11] = Ake;
  state[12] = Aki;
  state[13] = Ako;
  state[14] = Aku;
  state[15] = Ama;
  state[16] = Ame;
  state[17] = Ami;
  state[18] = Amo;
  state[19] = Amu;
  state[20] = Asa;
  state[21] = Ase;
  state[22] = Asi;
  state[23] = Aso;
  state[24] = Asu;

  return 0;
}

KINLINE void _keccakf_aligned(uint64_t* const A) {
  _keccakp(A, 24);
}
