#ifndef KECCAK_KECCAK_KECCAKP_1600_KECCAKP_TINY64_H
#define KECCAK_KECCAK_KECCAKP_1600_KECCAKP_TINY64_H
#include <stdint.h>
static const uint8_t rotation_constants[24] = {1,
                                               3,
                                               6,
                                               10,
                                               15,
                                               21,
                                               28,
                                               36,
                                               45,
                                               55,
                                               2,
                                               14,
                                               27,
                                               41,
                                               56,
                                               8,
                                               25,
                                               43,
                                               62,
                                               18,
                                               39,
                                               61,
                                               20,
                                               44};
static const uint8_t pi_lanes[25] = {10,
                                     7,
                                     11,
                                     17,
                                     18,
                                     3,
                                     5,
                                     16,
                                     8,
                                     21,
                                     24,
                                     4,
                                     15,
                                     23,
                                     19,
                                     13,
                                     12,
                                     2,
                                     20,
                                     14,
                                     22,
                                     9,
                                     6,
                                     1};
#endif  // KECCAK_KECCAK_KECCAKP_1600_KECCAKP_TINY64_H
